services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    volumes:
      - ./backend/uploaded:/app/uploaded

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "10001:80"
    volumes:
      - ./logs:/var/log/nginx
