name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. SSH로 서버에 접속
      - name: SSH to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}

      # 3. Docker Compose로 빌드 및 배포
      - name: Build and deploy with Docker Compose
        run: |
          cd /Users/codingserver/Desktop/sesac-project
          git pull
          docker-compose down --rmi local
          docker-compose build --no-cache
          docker-compose up
